// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj9iHiCi1TVIcuKJNAbDsh0SKoJ36vxaI',
    appId: '1:565725334351:android:92a40ac25a82cef88f933a',
    messagingSenderId: '565725334351',
    projectId: 'course-work-faee7',
    databaseURL: 'https://course-work-faee7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'course-work-faee7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUcsGoMUHO6kUWYkWWNC5_pCeBHvHTmY',
    appId: '1:565725334351:ios:cb2dedc572d460028f933a',
    messagingSenderId: '565725334351',
    projectId: 'course-work-faee7',
    databaseURL: 'https://course-work-faee7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'course-work-faee7.firebasestorage.app',
    iosBundleId: 'com.example.yogaClient',
  );
}
